name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.6.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.6.9'  # use 3.x to use the most up-to-date python3 version
          architecture: 'x64' # Optional - x64 or x86 architecture, defaults to x64
      - name: Print content of src folder
        run: ls -l /home/runner/work/HerediVar/HerediVar/src
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install wheel setuptools
          python3 -m pip install --upgrade setuptools wheel
          pip install pytest
          pip install -e src/common
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      #- name: Lint with flake8
      #  run: |
      #    # stop the build if there are Python syntax errors or undefined names
      #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Start web service
        run: |
          chmod 755 src/frontend_celery/start_webapp.sh
          src/frontend_celery/start_webapp.sh
        shell: bash
      - name: Something
        run: echo "TEST"