name: ci frontend

on: [push]

jobs:

  build_python:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      - name: Set up Python 3.6.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.6.9'  # use 3.x to use the most up-to-date python3 version
          architecture: 'x64' # Optional - x64 or x86 architecture, defaults to x64
      - uses: actions/cache@v2 # cache the python environment to speed up tests
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install wheel setuptools
          python3 -m pip install --upgrade setuptools wheel
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      #- name: Lint with flake8
      #  run: |
      #    # stop the build if there are Python syntax errors or undefined names
      #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics



  build_keycloak:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Update maven settings
        run: mkdir -p ~/.m2 ; cp .github/settings.xml ~/.m2/

      - name: Cache Maven repo
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/keycloak
          key: cache-1-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-1-${{ runner.os }}-m2

      - name: Prepare Keycloak
        run: src/frontend_celery/tests/script/prepare_keycloak.sh

      #- name: Start Keycloak
      #  run: scripts/start-local-server.sh




  test_frontend:
    runs-on: ubuntu-latest
    needs: [build_python, build_keycloak]

    steps:
      - name: run tests
        run: src/frontend_celery/tests/script/run_tests.sh
        shell: bash